{"componentChunkName":"component---src-templates-post-js","path":"/docker-vpn-memo/","result":{"data":{"site":{"siteMetadata":{"title":"mojaie.github.io","siteUrl":"https://mojaie.github.io","author":{"name":"Seiji Matsuoka","summary":"Cheminformatics, Biointeraction and Laboratory automation"},"license":"CC BY 4.0","licenseURL":"https://creativecommons.org/licenses/by/4.0/legalcode","social":{"twitter":"mojaie"}}},"markdownRemark":{"id":"a3a67a96-2b07-5abe-8a7b-60bf2cb67af0","excerpt":"環境 クライアント: MacOS 11.6.1 F5 VPN サーバ: Ubuntu 20.04.3 LTS Docker Engine 20.10.12 Docker Compose 1.25.0 構成 自宅MacからVPNで職場のネットワークにあるサーバに接続 サーバはPostgreSQL…","html":"<h3>環境</h3>\n<ul>\n<li>\n<p>クライアント: MacOS 11.6.1</p>\n<ul>\n<li>F5 VPN</li>\n</ul>\n</li>\n<li>\n<p>サーバ: Ubuntu 20.04.3 LTS</p>\n<ul>\n<li>Docker Engine 20.10.12</li>\n<li>Docker Compose 1.25.0</li>\n</ul>\n</li>\n</ul>\n<h3>構成</h3>\n<ul>\n<li>自宅MacからVPNで職場のネットワークにあるサーバに接続</li>\n<li>サーバはPostgreSQLでデータベースを構築してあり、Docker-composeでPostgreSQLとPostgRESTを起動し、自宅からHTTP接続でデータを取得している</li>\n</ul>\n<h3>現象</h3>\n<p>docker-compose upしたらエラーになり、その後一切SSHでサーバに接続できなくなった</p>\n<h3>原因</h3>\n<p>ネットワーク障害かと思って情シスに問い合わせたところ、特に異常はないとのこと。サーバ側でクライアントを遮断しているのでは?sshdのログやiptablesを確認してみてねとのこと。</p>\n<p>出勤して職場内の別の端末からサーバにSSH接続すると普通に接続できた。言われた通りiptablesを確認してみると、Chain DOCKERのdestinationが172.31.0.2になっているレコードあり。なんだこれは。</p>\n<div class=\"gatsby-highlight\" data-language=\"text\"><pre class=\"language-text\"><code class=\"language-text\">(server) user@hogehoge:~$ docker network ls\nNETWORK ID     NAME             DRIVER    SCOPE\nbd6daba0ee1d   bridge           bridge    local\n64ed5ca6e3c3   host             host      local\n53fd71b61b86   none             null      local\n8888ff4c812c   server_default   bridge    local</code></pre></div>\n<p>Docker-composeは自動的にプロジェクト名_defaultというネットワークを作成して各コンテナに空いているIPを割り当てるらしい。docker network inspectするとネットワークの詳細が確認できる。</p>\n<div class=\"gatsby-highlight\" data-language=\"text\"><pre class=\"language-text\"><code class=\"language-text\">(server) user@hogehoge:~$ docker network inspect 8888ff4c812c\n[\n    {\n        &quot;Name&quot;: &quot;server_default&quot;,\n        (中略)\n        &quot;IPAM&quot;: {\n            &quot;Driver&quot;: &quot;default&quot;,\n            &quot;Options&quot;: null,\n            &quot;Config&quot;: [\n                {\n                    &quot;Subnet&quot;: &quot;172.31.0.0/16&quot;,\n                    &quot;Gateway&quot;: &quot;172.31.0.1&quot;\n                }\n            ]\n        },\n        (中略)\n    }\n]</code></pre></div>\n<p>Subnetで172.31.0.0/16の範囲が割り当てられている。これが原因のような気がするので<code class=\"language-text\">docker network rm</code>で削除して帰宅。</p>\n<div class=\"gatsby-highlight\" data-language=\"text\"><pre class=\"language-text\"><code class=\"language-text\">(server) user@hogehoge:~$ docker network rm 8888ff4c812c\n8888ff4c812c</code></pre></div>\n<p>自宅から再度VPN経由でSSH接続してみると普通につながる。やはりDocker networkが原因だったようだ。VPNの設定のルーティングテーブルを見てみると職場内ネットワークIPへのアクセスを172.31.30.49に回す設定になっているので、IPアドレスが競合しているようだ…</p>\n<h3>対策</h3>\n<p>Composeファイルで明示的にネットワークを指定する。</p>\n<p>参考: Compose file version 3 referenceのipv4_address, ipv6_addressあたり\n<a href=\"https://docs.docker.com/compose/compose-file/compose-file-v3/\">https://docs.docker.com/compose/compose-file/compose-file-v3/</a></p>\n<div class=\"gatsby-highlight\" data-language=\"text\"><pre class=\"language-text\"><code class=\"language-text\">version: &quot;3.7&quot;\n\nservices:\n  app1:\n    image: image1\n    networks:\n      network1:\n        ipv4_address: 172.233.0.2\n  app2:\n    image: image2\n    networks:\n      network1:\n        ipv4_address: 172.233.0.3\n\nnetworks:\n  network1:\n    ipam:\n      driver: default\n      config:\n        - subnet: &quot;172.233.0.0/16&quot;</code></pre></div>\n<p>トップレベル要素のnetworksの下にネットワーク名(例ではnetwork1)、その下のipam、configで、VPNとかぶらないサブネットの範囲を指定する。さらに、servicesの下のそれぞれのサービスにnetworks要素を作成し、ネットワーク名、ipv4_addressで先程のサブネット内のアドレスを指定する。ゲートウェイを指定しない場合、範囲の先頭のアドレス(例では172.233.0.1)が自動的にゲートウェイに割り当てられるので、それ以外のアドレスにする。</p>","fields":{"slug":"/docker-vpn-memo/"},"frontmatter":{"title":"VPN経由でDocker compose upするとサーバに接続できなくなった","dateCreated":"January 06, 2022","dateModified":"January 06, 2022","tags":["Docker","SSH","VPN","network","remote"],"description":null}},"file":null},"pageContext":{"slug":"/docker-vpn-memo/","draft":false,"image":null,"previous":{"fields":{"slug":"/environment-memo/"},"frontmatter":{"title":"作業環境構築メモ","image":null,"draft":false}},"next":{"fields":{"slug":"/pyenv-lzma/"},"frontmatter":{"title":"pyenvでlzmaがない警告 (MacOS)","image":null,"draft":false}}}},"staticQueryHashes":["2841359383","3266777773","401191528"]}